# Generated by Django 3.1.4 on 2021-06-20 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_auto_20210620_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userweight',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='userweight',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
