# Generated by Django 3.1.4 on 2021-06-20 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20210620_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userweight',
            name='user',
        ),
        migrations.AddField(
            model_name='userweight',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.userprofile'),
        ),
    ]
