# Generated by Django 3.1.4 on 2021-06-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20210620_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calories',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='carbs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='proteines',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
