# Generated by Django 3.1.4 on 2021-06-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20210621_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('proteine', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('carb', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('userprofile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.userprofile')),
            ],
        ),
    ]
