# Generated by Django 3.1.4 on 2021-06-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_usernutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernutrition',
            name='foodName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usernutrition',
            name='foodWeight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
