# Generated by Django 3.1.4 on 2021-06-30 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20210627_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernutrition',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 30)),
        ),
    ]
