# Generated by Django 3.1.4 on 2021-06-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20210630_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernutrition',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
